import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

import { trpc } from "../utils/api";

interface FormData {
  title: string;
  description: string;
}

const NewNote: NextPage = () => {
  const [data, setData] = useState<FormData>({
    title: "",
    description: "",
  });

  const utils = trpc.useContext();

  const addNewNote = trpc.mynotes.newNote.useMutation({
    onMutate: () => {
      utils.mynotes.allNotes.cancel();
      const optimisticUpdate = utils.mynotes.allNotes.getData();

      console.log('onMetate', optimisticUpdate);
      

      if (optimisticUpdate) {
        utils.mynotes.allNotes.setData(undefined, optimisticUpdate);
      }
    },
    onSettled: () => {
      utils.mynotes.allNotes.invalidate();
    },
  });
  // console.log(addNewNote.data);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto flex min-h-screen flex-col justify-center py-10 md:container">
        <Link
          href={"/"}
          className="indigo-700  inline-block py-4 text-base font-semibold leading-7 text-green-700"
        >
          Go back
        </Link>
        <h1 className="mb-6 text-left text-3xl font-bold tracking-tight text-gray-900"></h1>
        <form
          onSubmit={(e: React.FormEvent) => {
            e.preventDefault();
            addNewNote.mutate({
              title: data.title,
              description: data.description,
            });
          }}
        >
          <input
            type="text"
            required
            value={data.title}
            placeholder="Your title"
            onChange={(e) => setData({ ...data, title: e.target.value })}
            className="border-1 mb-2 w-full rounded-sm border-green-800 bg-neutral-100 px-4 py-2 focus:outline-none"
          />
          <br />
          <textarea
            typeof="text"
            required
            value={data.description}
            placeholder="Your description"
            onChange={(e) => setData({ ...data, description: e.target.value })}
            className="border-1 mb-2 block w-full rounded-sm border-green-800 bg-neutral-100 px-4 py-2 focus:outline-none"
          />
          <button
            type="submit"
            className="block w-full rounded-lg bg-green-600 px-4 py-1.5 text-base font-semibold leading-7 text-white shadow-sm ring-1 ring-green-600 hover:bg-green-700 hover:ring-green-700"
          >
            Add a note
          </button>
        </form>
      </main>
    </>
  );
};

export default NewNote;
