import React, { ChangeEventHandler, useEffect, useState } from "react";
import { trpc } from "../../utils/api";
import { useRouter } from "next/router";
import Head from "next/head";
import Link from "next/link";

type FormData = {
  title: string;
  description: string;
  id: string;
};

const EditNote = () => {
  const utils = trpc.useContext();

  const [data, setData] = useState<FormData>({
    id: "",
    title: "",
    description: "",
  });

  const router = useRouter();
  const noteId = router.query.id as string;

  const { data: noteData, isLoading } = trpc.mynotes.detailNote.useQuery({
    id: noteId,
  });

  useEffect(() => {
    if (noteData) {
      setData({
        title: noteData.title,
        description: noteData.description,
        id: noteData.id,
      });
    }
  }, [noteData]);

  const updateNote = trpc.mynotes.updateNote.useMutation({
    onMutate: () => {
      utils.mynotes.allNotes.cancel();

      const optimisticUpdate = utils.mynotes.allNotes.getData();

      if (optimisticUpdate) {
        utils.mynotes.allNotes.setData(undefined, optimisticUpdate);
      }
    },
    onSettled: () => {
      utils.mynotes.allNotes.invalidate();
      utils.mynotes.detailNote.invalidate();
    },
    onSuccess: () => {
      router.push("/");
    },
  });

  if (isLoading) return <>Loading...</>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto flex min-h-screen flex-col justify-center py-10 md:container">
        <Link
          className="indigo-700 inline-block py-4 text-base font-semibold leading-7 text-green-700"
          href="/"
        >
          Go back
        </Link>
        <h1 className="mb-6 text-left text-3xl font-bold tracking-tight text-gray-900">
          Edit your note
        </h1>
        <form
          onSubmit={(event) => {
            event.preventDefault();
            updateNote.mutate({
              title: data.title,
              description: data.description,
              id: data.id,
            });
            setData({
              title: "",
              description: "",
              id: "",
            });
          }}
        >
          <input
            type="text"
            required
            value={data?.title}
            placeholder="Your title"
            onChange={(event) =>
              setData({ ...data, title: event.target.value })
            }
            className="border-1 mb-2 block w-full rounded-sm border-green-800 bg-neutral-100 px-4 py-2 focus:outline-none"
          />
          <textarea
            typeof="text-area"
            required
            value={data?.description}
            placeholder="Your description"
            onChange={(event) =>
              setData({ ...data, description: event.target.value })
            }
            className="border-1 mb-2 block w-full rounded-sm border-green-800 bg-neutral-100 px-4 py-2 focus:outline-none"
          />
          <button
            type="submit"
            className="block w-full rounded-lg bg-green-600 px-4 py-1.5 text-base font-semibold leading-7 text-white shadow-sm ring-1 ring-green-600 hover:bg-green-700 hover:ring-green-700"
          >
            Edit a note
          </button>
        </form>
      </main>
    </>
  );
};

export default EditNote;
